### ISSUE TITLE
css "[edit this page]" in the way

### ISSUE THREAD

**Issue by coding-saints** [lhunath/bash.academy#2] opened 2015-12-15 18:52 UTC
Not sure how big a deal...
"[edit this page]" hover needs changed: transparent font, or a more light RGB.
I'd give an example, but just about any config. to push it more in the right corner will do

**Comment by lhunath** [comment] 2015-12-15 20:39
I'm unsure what the problem is with the way it is now.  Can you illustrate or perhaps provide a screenshot?

**Comment by coding-saints** [comment] 2015-12-15 21:46
here are 2 screen shots
sorry, new to this, just trying to help
2nd image is of favicon not showing(again, not sure if these are big deals)
along with the menu Icon hovering over text...
Maybe set both as a fixed-nav? this way those 2 icons always stay on top
and the content will "disappear" when it hits nav screen.
NIck

On Tue, Dec 15, 2015 at 3:39 PM, Maarten Billemont <notifications@github.com

> wrote:
> 
> I'm unsure what the problem is with the way it is now. Can you illustrate
> or perhaps provide a screenshot?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lhunath/bash.academy/issues/2#issuecomment-164889843.

## 

CODING-SAINTS.COM

**Comment by lhunath** [comment] 2015-12-15 21:50
You didn't actually attach anything.  Try using GitHub directly to attach files to this issue rather than email replies.

**Comment by coding-saints** [comment] 2015-12-15 22:01
thats weird, hold on a sec ill get on

On Tue, Dec 15, 2015 at 4:54 PM, Maarten Billemont <notifications@github.com

> wrote:
> 
> You didn't actually attach anything. Try using GitHub directly to attach
> files to this issue rather than email replies.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lhunath/bash.academy/issues/2#issuecomment-164908084.

## 

CODING-SAINTS.COM

**Comment by coding-saints** [comment] 2015-12-15 22:01
![bash1](https://cloud.githubusercontent.com/assets/15819862/11825527/81fcda88-a34d-11e5-9585-b68a64505352.png)
![bash2](https://cloud.githubusercontent.com/assets/15819862/11825528/820c562a-a34d-11e5-9614-88de42fdb563.png)

**Comment by romanlevin** [comment] 2015-12-17 08:34
The problem is that this looks awkward and is distracting when reading:
![screenshot from 2015-12-17 09-28-33](https://cloud.githubusercontent.com/assets/132421/11864952/053db9c2-a4a1-11e5-9875-5b6f8f9426b7.png)

One possible solution would be to simply add a white background.
![screenshot from 2015-12-17 09-29-05](https://cloud.githubusercontent.com/assets/132421/11864965/1d9134c2-a4a1-11e5-8b38-e227ec7a91c3.png)

Lowering opacity a bit might be more palatable, depending on taste.
![screenshot from 2015-12-17 09-30-39](https://cloud.githubusercontent.com/assets/132421/11864988/4372ac3e-a4a1-11e5-958f-c26b1680ccf7.png)

**Comment by lhunath** [comment] 2015-12-17 13:43
Should be fixed; let me know if you still have issues with the fix.

**Closed as completed by lhunath** 2015-12-17 13:43 UTC
